### ISSUE TITLE
can  pixel deconvolutional layer directly used to other models?

### ISSUE THREAD

**Issue by daixiaogang** [xiao9aba2008/DilatedPixelCNN#37]
Thanks for your code! Can I directly change the tf.nn.conv2dtranspose() to pixel deconvolutional layer?

**Comment by HongyangGao** [comment]
sure, if your up-sampling factor is 2. For example from 2x2 to 4x4.

**Comment by daixiaogang** [comment]
Tanks! If  up-sampling factor is higher(eg.4),what should I do?

**Comment by HongyangGao** [comment]
Current it only support factor 2. If you want to up by 4, you can use it twice.
