### ISSUE TITLE
Error when saving predictions of PixelDCN

### ISSUE THREAD

**Issue by Jumabek** [xiao9aba2008/DilatedPixelCNN#45]
Hi thx for the amazing work!

I am trying prediction example on the source code and as usual I have an error which I cannot solve (at least not yet). 
Could you please help me Debug this.

The error is occuring in the following line:
https://github.com/HongyangGao/PixelDCN/blob/master/network.py#L280

Thank you.

And this is the call Stack:
```
---->predicting
inputs.shape:  (1, 16, 256, 256, 1)
----->saving predictions
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    tf.app.run()
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 22, in main
    getattr(model, args.option)()
  File "E:\code\FireSegmentation\PixelDCN\network.py", line 287, in predict
    str(index*prediction.shape[0]+i)+'.png')
  File "E:\code\FireSegmentation\PixelDCN\utils\img_utils.py", line 44, in imsave
    if k < 21:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by HongyangGao** [comment]
Hi, actually this code is for 2D data, which means the input should be 1xHxWxC. It seems your input is a 3D data. you need to change the code according to your expectation. For example, you can change the code in line 287 in network.py to:
`str(index*prediction.shape[0][0]+i)+'.png')`

**Comment by Jumabek** [comment]
Yep, that works like a charm,
Thank your for a quick reply!
