### ISSUE TITLE
 parameter question

### ISSUE THREAD

**Issue by watchmexiang** [xiao9aba2008/DilatedPixelCNN#50]
Hello, I want to replace Transposed Convolution with Pixel Transposed Convolution, which you share. I used pixel_dcl of your pixel_dcn directly, but there is a parameter scope that I don't know what to fill in. What does this parameter relate to and how to fill in?

**Comment by HongyangGao** [comment]
Hi there,

Thank you for your interests. Scope is a parameter to control the namespace of you parameters. It's just like the parameter of "name" in layers like tf.layers.conv2d_transpose. Hope this helps.
