### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by Ahalang** [xiao9aba2008/DilatedPixelCNN#52]
Hello, could u tell me where can I get the pretrained model? Thank you.

**Comment by HongyangGao** [comment]
Hi there,

I created a shared file using google drive. https://drive.google.com/file/d/1D03t4SBWKvSgtx4ZEB0iKctTdiojXCF_/view?usp=sharing
https://drive.google.com/file/d/1yc-WAnZZ1axhe1MIOcKnjke2DWzZPdjI/view?usp=sharing
